Update pipelines.py
pipelines.py send the items stored in items.py to the mysql databse. Currently working on solving the current error:
mysql.connector.errors.ProgrammingError: Failed processing format-parameters; Python 'list' cannot be converted to a MySQL type

Lines 41 and 42. Those two variables are lists containing multiple possible hashtags